id: P140F3D0A
initial_creation_type: ocr
source_metadata:
  volumes:
    d25fdf92830341949c67ae9896b0a0a5:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཡོན་ཏན་མཐའ་ཡས་པར་བསྟོད་པའི་འགྲེལ་པ།
      total_pages: 1539
      volume_number: 1
