id: DB6B6B62E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:54:02+00:00'
last_modified: '2022-05-26T06:09:29.774648+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '8366':
      image_group_id: I1PD95846
      title: ཡོན་ཏན་མཐའ་ཡས་པར་བསྟོད་པའི་འགྲེལ་པ།
      total_pages: 1539
      order: 1
      base_file: 8366.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
